week2_hw_5번까지
Soob00/nest-study-eventory pull request #2
Opened 2024-11-03 14:09 UTC by Soob00

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [o] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
week2 hw의 post, get 기능 구현 (14,16,17,18,19)

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
정확히 구현되었는지 잘 모르겠네요ㅠ 코멘트 남겨주시면 수정해보겠습니다!

추가로 질문이 있는데, schema.prisma의 경우 prisma에서 가져올 때 자동으로 생성되는 것이고, 저희가 실제로 개발을 할 때 신경쓰는 것은 dto, payload, query, type, controller, module, repository, service라고 이해해도 될까요?

감사합니다! 

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-03 15:12 UTC, worjs requested changes
양이 좀 많았는데 고생하셨습니다!
코멘트 읽어보시고 수정해서 리뷰 다시 request해주시면 보러올게요!

prisma.schema에 대한 부분은 4주차 수업에서 다룰 예정이고, 서버 코드는 말씀하신 요소들로 이루어져 있다고(더 추가해도 되고요) 이해하시면 되겠습니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
Post 요청으로 객체가 생성된 경우에는 201 Created!
`ApiCreatedResponse`를 사용해야합니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
만약에 id에 숫자가 아닌 string을 넣어서 요청하게되면...?
서버 켜고 `localhost:3000/events/aaa`요기로 접속해보면 확인할 수 있습니다!

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
수업에서 다루는걸 까먹었는데 `@HttpCode(204)`를 해줘야 204가 내려오더라구요. Post는 기본으로 201을 내려주네요.

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
payload 타입 이름이 create~~인데, 막상 이 api와 함수는 생성과는 관련이 없는 기능을 수행하고 있어요.
혼용가능한 적절한 이름을 짓는게 좋겠습니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
endTime은 어떤 이유로 있는 변수인가요?

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
요건 어떤 이유로 구현하셨나요??

2024-11-03 15:12 UTC, worjs commented on src/event/event.repository.ts
> +    }
Nestjs에서는 적절한 Exception타입을 사용해서 에러를 던져야 Response로 나갑니다.
이 경우는 404. 즉, `NotFoundException`을 던지는게 좋겠습니다.

2024-11-03 15:12 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
이거 혹시 직접 테스트해보셨나요? 아마 아무리 테스트해도 에러가 뜰건데, 이는 런타임에서 막 요청 바디가 객체로 매핑될 때, string으로 매핑되기 때문입니다. 따라서 적절히 Date 타입 검증을 통과하기 위해서는 string을 Date 타입으로 바꿔줘야 하는데, `@Type(() => Date)`를 활용하면 됩니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    }
얘는 409 Conflict보다는 400 BadRequest가 맞습니다. 당장 값 자체만 보더라도 틀린 것이 판단이 되니까요.
Payload에서 validator로 처리할 수 있을 것 같습니다. 아래 docs 참고해주세요
https://github.com/typestack/class-validator

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    }
title이 중복되면 안된다는 요구사항이 없었긴 합니다(?)

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    }
얘도 400 BadRequest가 맞습니다. 마찬가지로 payload클래스에서 validator로 처리하면 좋겠지만 아마 쉽지 않아서 그냥 BadRequest로 리턴하는 정도면 좋을 것 같네요.

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +      id: generateUniqueId(),
음 일반적으로 db는 id를 자체적으로 생성해주는 편입니다.
우리 프로젝트의 경우에도 db에서 auto_increment로 1부터 차례로 숫자를 부여하고 있어서, 이 부분은 따로 지정하실 필요 없을 것 같아요.

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +      },
status의 경우에는 요구사항에는 있지만, DB 스키마를 살펴보시면 따로 저장하는 곳이 없습니다.
그렇게 할 필요가 없기 때문인데요, status의 3단계를 잘 보시면 startTime, endTime과 현재 시간 간의 관계를 통해 우리가 따로 구할 수 있기 때문에 별도로 status를 중복해서 저장할 필요가 없습니다.

2024-11-03 15:12 UTC, worjs commented on src/event/type/create-event-data.ts
> +};
리소스 생성을 위해 데이터를 담아두는 타입입니다.
딱 repository가 리소스를 생성할 때 필요한 필드들만 정의하시면 되겠습니다~

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +  }
???

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +  async createEvent(payload: CreateEventPayload): Promise<EventDto> {
아직 처리되지 않은 예외사항들이 더 있습니다!

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    const maxPeople = await this.eventRepository.getMaxPeople(eventId);
이거 전부 다 findEventById로 조회해온 event 가지고도 할 수 있지 않을까요

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    await this.eventRepository.joinEvent(userId, joinPayload);
첫번째 인자로 userId를 받았는데, 굳이 다음 인자로 또 넣어주신{eventId, userId} 이유가 있나요?

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    const maxPeople = await this.eventRepository.getMaxPeople(eventId);
이벤트가 종료되었습니다, 이벤트가 시작되었습니다.
만 듣고는 api를 사용하는 개발자 입장에서 그래서 어쩌라고..? 라는 생각이 들 수도 있어보여요.
더 확실하게 `이미 종료된 이벤트에 참가할 수 없습니다.`등과 같이 명확한 에러 메세지를 작성하는게 좋습니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.controller.ts
> +  }
경로 파라미터로 eventId를 받아왔는데 payload로 또 eventId를 받을 필요가 있을까요?

2024-11-03 15:12 UTC, worjs commented on src/event/event.repository.ts
> +  getJoinedPeople: any;
???

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +  async leaveEvent(eventId: number, userId: number): Promise<void> {
호스트가 나가려고 하는 경우도 생각해주어야 합니다.

2024-11-03 15:12 UTC, worjs commented on src/event/event.service.ts
> +    }
등호로도 충분하지 않을까요?

2024-11-03 17:47 UTC, Soob00 commented on src/event/event.service.ts
> +  async leaveEvent(eventId: number, userId: number): Promise<void> {
네 수정해보겠습니다!

2024-11-03 17:54 UTC, Soob00 commented on src/event/event.service.ts
> +    const maxPeople = await this.eventRepository.getMaxPeople(eventId);
아 그렇네요 event의 역할을 잘 이해하지 못했던 것 같아요. 수정해보겠습니다!

2024-11-03 17:56 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
네 수정해보겠습니다!

2024-11-03 17:57 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
오 이건 생각해보지 못했네요. 수정해보겠습니다!

2024-11-03 17:57 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
경로 파라미터에 대한 이해가 부족했던 것 같아요. 수정해보겠습니다!

2024-11-03 17:59 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
코드에 대한 이해가 부족했던 것 같아요 삭제해보겠습니다!

2024-11-03 18:00 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
이것도 다시 생각해보니 없어도 될 것 같네요 ㅎㅎ

2024-11-03 18:00 UTC, Soob00 commented on src/event/event.repository.ts
> +    }
네 수정해보겠습니다!

2024-11-03 18:03 UTC, Soob00 commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
아 테스트는 못해봤었는데 이러 문제가 있었군요.. 기억해두고 수정해보겠습니다!

2024-11-03 18:07 UTC, Soob00 commented on src/event/event.service.ts
> +    }
네 수정해보겠습니다!

2024-11-03 18:08 UTC, Soob00 commented on src/event/event.service.ts
> +    }
아 그렇네요..,

2024-11-03 18:08 UTC, Soob00 commented on src/event/event.service.ts
> +    }
네 수정해보겠습니다!

2024-11-03 18:08 UTC, Soob00 commented on src/event/event.service.ts
> +      id: generateUniqueId(),
넵!

2024-11-03 18:09 UTC, Soob00 commented on src/event/event.service.ts
> +      },
db도 잘 이해해야겠네요. 수정해보겠습니다!

2024-11-03 18:09 UTC, Soob00 commented on src/event/type/create-event-data.ts
> +};
넵!

2024-11-04 03:44 UTC, Soob00 commented on src/event/event.controller.ts
> +  }
이것과 관련해서 localhost:3000/events/123을 실행해보려고 swagger로 event를 추가해보았습니다. (swagger에 추가하면 연결되는 게 맞는걸까요??)
후에 다시 위 url을 실행하니, 추가한 카테고리 id 등이 존재하지 않는다고 나와서요! 이런 카테고리id의 선택지는 어떻게 확인할 수 있나요? 직접 추가해주어야 하는 건가요?

2024-11-04 03:47 UTC, Soob00 commented on src/event/event.service.ts
> +  async createEvent(payload: CreateEventPayload): Promise<EventDto> {
넵 수정해보았습니다!

2024-11-04 03:50 UTC, Soob00 commented on src/event/event.service.ts
> +    await this.eventRepository.joinEvent(userId, joinPayload);
payload에 대한 이해가 조금 부족했던 것 같아요ㅠ
controller가 사용자가 요청한 것을 확인하기 위해 payload가 필요한 것이고,
service, repository에서는 payload를 따로 사용하지 않고 eventId 같은 것을 그냥 사용하면 되는 건가요?

2024-11-04 03:51 UTC, Soob00 commented on src/event/event.repository.ts
> +  getJoinedPeople: any;
이 부분은 필요하지 않을 것 같아 삭제해보았습니다!

2024-11-04 03:51 UTC, Soob00 commented on src/event/event.service.ts
> +    }
확인했습니다!

2024-11-04 03:51 UTC, Soob00 commented on src/event/event.service.ts
> +  }
오류 해결하느라 불필요한 코드들을 확인 못했네요.., 필요하지 않을 것 같아서 삭제해보았습니다!

2024-11-04 05:16 UTC, worjs requested changes
조금만 더 화이팅!

2024-11-04 05:16 UTC, worjs commented on src/event/dto/event.dto.ts
> +  maxPeople!: number;
음 여기는 내보내는 데이터를 담는 DTO라 데이터를 검증할 필요가 없어요

2024-11-04 05:16 UTC, worjs commented on src/event/event.repository.ts
> +  }
이렇게 작성하면 원하는 결과를 얻지 못할거예요!
먼저 EventJoin 테이블을 한번 확인해보시고, 어떤 것을 조건으로 어떤 정보를 얻고 싶은지 고민해보시면 좋을 것 같네요!

2024-11-04 05:16 UTC, worjs commented on src/event/event.repository.ts
> +  }
얘네들은 안쓰는 코드가 된거죠 이제?

2024-11-04 05:16 UTC, worjs commented on src/event/type/create-event-data.ts
> +  JoinUser: number;
이 필드의 용도는 무엇인가요?

2024-11-04 05:16 UTC, worjs commented on src/event/event.repository.ts
> +  }
JoinedPeople이라는 이름은 이게 가입된 사람들의 정보를 뜻하는 것인지, 가입된 사람들의 숫자를 뜻하는 것인지 의미가 모호한 것 같아요.

2024-11-04 05:16 UTC, worjs commented on src/event/event.service.ts
> +    }
이 검증은 class-validator를 활용해서 Payload class에서 이루어지고 있는 것들이예요.
review쪽에서 Post /reviews 구현 코드와, 2주차 강의자료에서 400, 404, 409에 대한 부분을 한번 보시면 감 잡는데 도음이 될 것 같네요!

2024-11-04 05:16 UTC, worjs commented on src/event/event.service.ts
> +  async joinEvent(eventId: number, userId: number): Promise<void> {
이 userId가 실제로 존재하는 user가 아니라면 어떻게 될까요?

2024-11-04 05:16 UTC, worjs commented on src/event/event.service.ts
> +    await this.eventRepository.joinEvent(userId, joinPayload);
우리가 지금 열심히 만들고 있는 WAS(Web Application Server) 혹은 Api 서버가 하는 일은, 사용자가 우리 서버로 HTTP 요청을 보내면 그 요청에서 데이터를 가져와 작업을 한 뒤 다시 HTTP 요청을 만들어서 응답하는 일입니다.

Controller는 그러한 HTTP 요청을 받아서, 데이터를 꺼낸 뒤 우리가 쉽게 사용할 수 있는 함수 형태로 준비해주는 역할이죠.
Controller에서 @Body() 데코레이터를 사용하면, request의 body부분에 있는 데이터를 자바스크립트 객체 형태로 함수의 매개변수로 받아온 것 처럼 할 수 있게 됩니다.

문제는 이렇게 되면 자바스크립트의 동적 타입이라는 특성 상, 상대가 쌩뚱맞은 형태의 객체를 보냈더라도 그대로 프로그램이 돌아가게 됩니다. 이러면 어딘가에서 어라? userId가 없어요(userId가 undefined입니다)라는 식의 에러가 발생하면서 요청을 처리할 수 없게 됩니다.

물론 TypeScript를 사용해서 타입을 정의한다고 하더라도, TypeScript는 우리 코드에서나 존재하는 것이지 실행하면 자바스크립트 코드로 변환되어 실행되기 때문에, 런타임에서는 다른 형태의 객체가 들어와도 막을 수가 없습니다.
이 문제를 막기 위해 사용자가 요청을 보냈을 때, 해당 요청이 우리가 정의한 타입들에 맞아떨어지는지 검증하는 과정이 필요합니다. 
그것을 도와주는 라이브러리가 class-validator라는 녀석이고요, class형태로 요청 바디를 정의한 뒤, 독스에서 제공하는 다양한 데코레이터를 필드마다 적절하게 달기만 하면 실제로 들어온 값이 적절한 타입인지 확인하고, 틀리면 400을 알아서 리턴하게 됩니다.

위 부분이 큰 그림이었고, 질문하신 것에 답변을 조금 드리면,

1. payload가 필요한 이유는 class-validator의 도움을 받아 요청 바디를 검증하기 위한 것이고요, 인터넷에 예시를 찾아보면 다들 dto라고 정의해서 많이들 씁니다. 저는 응답 바디를 dto로 하는 것을 좋아해서 구분을 위해 payload라는 이름을 컨벤션으로 도입한 것이라고 보시면 됩니다.
2. 저는 service에서만 사용하고 repository에는 다른 타입을 사용합니다. repository가 payload를 사용하게 되는 것을 '의존한다'라고 하고, payload의 변경에 영향을 받는다라고 하기도 하는데요, 굳이 repository도 payload를 알아야 할 필요가 없다고 생각해서 분리했습니다.

2024-11-04 05:16 UTC, worjs commented on src/event/event.controller.ts
> +  }
일단 우리 데이터베이스는 저번에 supabase라는 곳에서 만들었는데, 거기 대시보드에 들어가면 현재 데이터의 현황을 볼 수 있습니다. 직접 테이블을 수정하고 데이터를 넣고 지우고 할 수도 있으니 참고하시면 되겠습니다!

 localhost:3000/events/123 를 실행했는데 `추가한 카테고리 id 등이 존재하지 않는다고 나와서요! ` 이렇게 될 수 있나? 하는 생각이 먼저 들었는데, 실행사진 보여주시면 도와드릴 수 있을 것 같네요.

그리고 category 데이터 정보는 위에서 알려드린대로 DB에서 직접 보셔도 되고, 저번 과제로 category를 보는 api를 구현하셨으니 그걸 통해서 보셔도 됩니다.

2024-11-04 07:30 UTC, Soob00 commented on src/event/dto/event.dto.ts
> +  maxPeople!: number;
네 수정하겠습니다!

2024-11-04 07:32 UTC, Soob00 commented on src/event/event.repository.ts
> +  }
아 eventjoin에서 받아오는거니까, eventId를 해야겠네요! joinedpeople도 변경해보겠습니다.

2024-11-04 07:32 UTC, Soob00 commented on src/event/event.repository.ts
> +  }
네! 삭제를 안 했었군요. 삭제하겠습니다!

2024-11-04 07:46 UTC, Soob00 commented on src/event/type/create-event-data.ts
> +  JoinUser: number;
모임의 시작 시간, 종료 시간, 최대 인원과, 참여자가 누구인지 정의하기 위해서 필요하다고 생각해서 추가했습니다! ( 그래서 event를 create 할 때 startTime~JoinUser가 필요하다고 생각했어요. )  join user의 경우에는 host Id를 추가해야 돼서 저렇게 작성했습니다!

2024-11-04 07:48 UTC, Soob00 commented on src/event/event.service.ts
> +    }
네 한 번 읽어보겠습니다 !

2024-11-04 08:32 UTC, worjs commented on src/event/type/create-event-data.ts
> +  JoinUser: number;
아 JoinUser만 여쭤본거였는데 위에까지 잡혔네요.
아무튼 막상 repository쪽 코드를 보면 사용하고 있지는 않더라구요?

2024-11-04 13:28 UTC, Soob00 commented on src/event/type/create-event-data.ts
> +  JoinUser: number;
아 schema에 있는 eventjoin을 써주어야 하는 게 맞나요? eventjoin으로 바꾸었습니다!

2024-11-04 13:29 UTC, Soob00 commented on src/event/event.service.ts
> +  async joinEvent(eventId: number, userId: number): Promise<void> {
아 반영하여 수정해보았습니다!

2024-11-04 14:06 UTC, worjs commented on src/event/type/create-event-data.ts
> +  JoinUser: number;
실제로 실행하는 코드는 this.prisma~~부분이 데이터베이스와 상호작용하는 부분입니다.
인자로 넣어주는 데이터 타입은 정말 필요한 필드들만 있으면 됩니다.
어차피 매개변수로 받아서 내가 꺼내쓰는거니까요!

결론을 말씀드리면 그냥 빼셔도 되지 않을까... 였습니다ㅎㅎ,,,

2024-11-04 15:50 UTC, worjs approved these changes
LGTM! 고생많이하셨습니다~~

머지하기 전에 로컬에서 main rebase해서 포스푸시하셔야 컨플릭트 없어질거예요

2024-11-04 15:54 UTC, Soob00 commented
이번 과제 하면서 전체적으로 잘 이해할 수 있었던 것 같아요. 꼼꼼하게 코멘트 해주셔서 감사합니다!

2024-11-04 16:00 UTC, worjs commented
원래 첫 두세 PR이 가장 힘들어요! 이거 하셨으면 앞으론 훨씬 쉬울겁니다~~
고생많으셨어요!!!

2024-11-05 03:18 UTC, merged