Update,Delete event
Soob00/nest-study-eventory pull request #3
Opened 2024-11-07 04:02 UTC by Soob00

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
update event, delete event

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-07 06:07 UTC, Soob00 commented
soft delete, user 삭제 전까지의 과제입니다!

2024-11-07 10:32 UTC, worjs requested changes
고생하셨습니다!

soft delete 변경에 따른 repo 수정도 같이 하신 것 같네요! userId와 관련된 조회 모든 부분을 고쳐야 하는데, 제가 보기에는 아직 빠진 부분이 있는 것 같습니다.

직접 찾아내실 수 있을 것 같아서, 코멘트 쓰면서 일부러 직접적인 정답을 드리지는 않았습니다. 혹시 감을 잡기 어려우시면 댓글 달아주시면 도와드릴게요!

2024-11-07 10:32 UTC, worjs commented on src/event/payload/patch-event.payload.ts
> +  endTime?: Date;
여기도 type이 null이 될 수도 있을 것 같네요!

2024-11-07 10:32 UTC, worjs commented on src/event/event.service.ts
> +    }
조건문이 이상한 것 같아요!

2024-11-07 10:32 UTC, worjs commented on src/event/event.service.ts
> +    }
시간 관련 접근은 좋은데, 아직 고려하지 않은 시간 관련 예외사항이 있습니다!

2024-11-08 01:31 UTC, worjs approved these changes
수정 끝나신 건가요? 수정 끝난 이후에는 오른쪽 위에 reviewers에 제이름 넣고 re-request해주시면 바로 확인해드릴 수 있을 것 같아요.

코멘트가 몇개 있기는 한데 기능상 문제가 되는 것들은 아니어서 반영하고 바로 마무리하셔도 될 것 같습니다!

2024-11-08 01:31 UTC, worjs commented on src/event/event.controller.ts
>  }
이게 아마 실행하면 실제로는 200이 내려오나 그럴거예요
@HttpCode(204) 해줘야 204가 내려갑니다.

2024-11-08 01:31 UTC, worjs commented on src/event/event.service.ts
> +    }
요거는 DB 내 상태와 정합성이 안맞는 상황이니까 Conflict가 맞을 것 같네요

2024-11-08 01:31 UTC, worjs commented on src/event/event.service.ts
> +      await this.eventRepository.CountJoinedPeople(eventId);
동사로 시작하는 변수 이름은 JS에서는 함수로 오인하기 쉬워요. count 같은 경우에는 명사도 동사도 되기는 한데 저는 이런 경우에 joinedPeopleCount라고 하던가 countOfJoinedPeople이라고 지을 것 같네요.

그리고 함수 이름은 camelCase 따라주세요~~

2024-11-08 01:31 UTC, worjs commented on src/event/event.service.ts
> +    }
요거 validation을 이미 payload에서 마치고 오는 것 같더라구요

2024-11-08 06:06 UTC, Soob00 commented
네 다음부터 그렇게 하겠습니다!

2024-11-08 06:06 UTC, Soob00 commented
> 수정 끝나신 건가요? 수정 끝난 이후에는 오른쪽 위에 reviewers에 제이름 넣고 re-request해주시면 바로 확인해드릴 수 있을 것 같아요.

네 다음부터 그렇게 하겠습니다!

2024-11-08 06:30 UTC, Soob00 commented on src/event/event.service.ts
> +      await this.eventRepository.CountJoinedPeople(eventId);
네 다른 변수들 이름도 바꾸어주었습니다

2024-11-08 06:32 UTC, merged